#!/bin/bash

function implode( )
{
  if [ $# -ne 2 ]
    then
      echo "implode: expected two parameters!"
      exit 1
    fi
    
    local arrayNmae=$1
    local item=''    
    local tStr=''
    
    eval `echo -n 'expArray=( ${'$1'[@]} )'`
    
      for item in ${expArray[*]}
	do
	  tStr="$tStr$item"
	done

    eval `echo -n $2="'$tStr'"`
    
}